# Generated by Django 4.1.7 on 2023-03-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230309_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='assento',
            name='disponivel',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
