# Generated by Django 4.1.7 on 2023-03-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classeviagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classeviagem',
            options={'verbose_name_plural': 'ClassesViagem'},
        ),
        migrations.AlterField(
            model_name='viagem',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classeviagem'),
        ),
    ]
