# Generated by Django 4.1.7 on 2023-03-23 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230309_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem',
            options={'verbose_name_plural': 'Viagens'},
        ),
        migrations.AlterField(
            model_name='viagem',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_destino', to='core.municipio'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_origem', to='core.municipio'),
        ),
    ]
