# Generated by Django 4.1.7 on 2023-03-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230309_0101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assentos',
            new_name='Assento',
        ),
    ]
