# Generated by Django 4.1.7 on 2023-03-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_classeviagem_options_alter_viagem_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='assentos_indisponiveis',
            field=models.TextField(blank=True),
        ),
    ]
