# Generated by Django 4.1.7 on 2023-03-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_viagem_assentos_indisponiveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_assento', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='passagem',
            old_name='nome',
            new_name='nome_passageiro',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.viagem'),
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='assentos_indisponiveis',
        ),
        migrations.AddField(
            model_name='viagem',
            name='assentos_indisponiveis',
            field=models.ManyToManyField(to='core.assentos'),
        ),
    ]
