# Generated by Django 4.1.7 on 2023-03-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assentos_rename_nome_passagem_nome_passageiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
    ]
